### ISSUE TITLE
Frequent adapter crashes

### ISSUE THREAD

**Issue by meikel-g** [arteck/ioBroker.hs100#157]
Recently the hs100 adapter crashes frequently and as a result gets automatically disabled. The errors are occuring with various HS110 sockets - sample log snippet below:

`<html>
<body>

Log snippet:
--
2022-08-06 11:07:38.670 - info: host.iobroker-NAS Restart adapter system.adapter.hs100.0 because enabled
2022-08-06 11:08:08.810 - info: host.iobroker-NAS instance system.adapter.hs100.0 started with pid 16567
2022-08-06 11:08:10.997 - info: hs100.0 (16567) starting. Version 2.1.2 in /opt/iobroker/node_modules/iobroker.hs100, node: v14.19.0, js-controller: 4.0.23
2022-08-06 11:08:11.072 - info: hs100.0 (16567) Start with IP : 192.168.2.187
2022-08-06 11:08:11.413 - info: hs100.0 (16567) Start with IP : 192.168.2.139
2022-08-06 11:08:11.436 - info: hs100.0 (16567) Start with IP : 192.168.2.211
2022-08-06 11:08:11.466 - info: hs100.0 (16567) Start with IP : 192.168.2.172
2022-08-06 11:08:21.476 - info: hs100.0 (16567) Start with IP : 192.168.2.170
2022-08-06 11:08:21.501 - info: hs100.0 (16567) Start with IP : 192.168.2.167
2022-08-06 11:08:24.608 - warn: hs100.0 (16567) getDevice Socket connection Timeout ip: 192.168.2.172 please reconnect the Device
2022-08-06 11:09:33.439 - error: hs100.0 (16567) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-08-06 11:09:33.441 - error: hs100.0 (16567) unhandled promise rejection: TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-06 11:09:33.441 - error: hs100.0 (16567) Error: TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-08-06 11:09:33.443 - error: hs100.0 (16567) TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-06 11:09:33.450 - info: hs100.0 (16567) cleaned everything up...
2022-08-06 11:09:33.451 - info: hs100.0 (16567) terminating
2022-08-06 11:09:33.452 - warn: hs100.0 (16567) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-08-06 11:09:34.084 - error: host.iobroker-NAS Caught by controller[1]: TCP 192.168.2.172:9999 Error: TCP Timeout after 10000ms
2022-08-06 11:09:34.089 - error: host.iobroker-NAS Caught by controller[1]: 192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-06 11:09:34.090 - error: host.iobroker-NAS Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-08-06 11:09:34.090 - error: host.iobroker-NAS Caught by controller[1]: at listOnTimeout (internal/timers.js:557:17)
2022-08-06 11:09:34.091 - error: host.iobroker-NAS Caught by controller[1]: at processTimers (internal/timers.js:500:7)
2022-08-06 11:09:34.091 - error: host.iobroker-NAS Caught by controller[1]: [Waschmaschine] device.send() Error: TCP Timeout after 10000ms
2022-08-06 11:09:34.095 - error: host.iobroker-NAS Caught by controller[1]: 192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-06 11:09:34.096 - error: host.iobroker-NAS Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-08-06 11:09:34.096 - error: host.iobroker-NAS Caught by controller[1]: at listOnTimeout (internal/timers.js:557:17)
2022-08-06 11:09:34.097 - error: host.iobroker-NAS Caught by controller[1]: at processTimers (internal/timers.js:500:7)
2022-08-06 11:09:34.098 - error: host.iobroker-NAS instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-06 11:09:34.100 - info: host.iobroker-NAS Restart adapter system.adapter.hs100.0 because enabled
2022-08-06 11:09:34.101 - warn: host.iobroker-NAS Do not restart adapter system.adapter.hs100.0 because restart loop detected

</body>
</html>`

Adapter version: 2.1.2
node.js version: 14.19.0
js-controller version: 4.0.23
Host type: Synology DS 718+

**Comment by neunteufels** [comment]
Same here since last night.

Adapter version: 2.1.2
Node.js: 14.20.0
NPM: 6.14.17
js-controller: 4.0.23
VM auf Synology DS220+

**Comment by neunteufels** [comment]
Crashes are getting more and more since the last 24 hours.
Restart of adapter does not help.
Restart of IOBroker does not help.
Restart of Virtual Machine does not help.

Any suggestions?

**Comment by meikel-g** [comment]
I noticed that the adapter stopped crashing after upgrading iobroker to node.js v16.16. 
I upgraded my Synology to DSM 7.1-42661 Update 4 at the same time, but I can't imagine that being the reason.
If @neunteufels can try the later node.js version and confirm my observation, I suppose the issue can then be closed - given that node.js v16 is the currently recommended version.

**Comment by neunteufels** [comment]
Unfortunately I had no time to try the upgrade of node.js yesterday.
I simply did a restart of the adapter somewhen in the evening and since that it is running again.
So I will wait now it it gets worse again and the try the update.

**Comment by neunteufels** [comment]
I now did the update of DSM to 7.1-42661 Update 4.
So far no changes visable. Adapter is stable.

**Comment by neunteufels** [comment]
Update of DSM did not help.
Frequent crashes started again in the night.
Next step is to update Node.js to the recommended version 16.16.0.

**Comment by neunteufels** [comment]
Update to Node.js 16.16.0 done.
At the moment the whole system is stable.
I will report again in a few days if this was the final solution for me.

**Comment by neunteufels** [comment]
Intermediate update: Adapter is stable since yesterday.

**Comment by meikel-g** [comment]
Bad news: The issue does not disappear with Node.js 16:

`

2022-08-16 02:37:25.388 - error: hs100.0 (12599) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2022-08-16 02:37:25.403 - error: hs100.0 (12599) unhandled promise rejection: TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-16 02:37:25.404 - error: hs100.0 (12599) Error: TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
2022-08-16 02:37:25.405 - error: hs100.0 (12599) TCP Timeout after 10000ms
192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-16 02:37:25.409 - info: hs100.0 (12599) cleaned everything up...
2022-08-16 02:37:25.410 - info: hs100.0 (12599) terminating
2022-08-16 02:37:25.411 - warn: hs100.0 (12599) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-08-16 02:37:26.034 - error: host.iobroker-NAS Caught by controller[1]: TCP 192.168.2.172:9999 Error: TCP Timeout after 10000ms
2022-08-16 02:37:26.036 - error: host.iobroker-NAS Caught by controller[1]: 192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-16 02:37:26.036 - error: host.iobroker-NAS Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-08-16 02:37:26.037 - error: host.iobroker-NAS Caught by controller[1]: at listOnTimeout (node:internal/timers:559:17)
2022-08-16 02:37:26.037 - error: host.iobroker-NAS Caught by controller[1]: at processTimers (node:internal/timers:502:7)
2022-08-16 02:37:26.037 - error: host.iobroker-NAS Caught by controller[2]: [Waschmaschine] device.send() Error: TCP Timeout after 10000ms
2022-08-16 02:37:26.037 - error: host.iobroker-NAS Caught by controller[2]: 192.168.2.172:9999 {"emeter":{"get_daystat":{"year":2022,"month":8}}}
2022-08-16 02:37:26.038 - error: host.iobroker-NAS Caught by controller[2]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-08-16 02:37:26.038 - error: host.iobroker-NAS Caught by controller[2]: at listOnTimeout (node:internal/timers:559:17)
2022-08-16 02:37:26.038 - error: host.iobroker-NAS Caught by controller[2]: at processTimers (node:internal/timers:502:7)
2022-08-16 02:37:26.038 - error: host.iobroker-NAS instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-16 02:37:26.039 - info: host.iobroker-NAS Restart adapter system.adapter.hs100.0 because enabled
2022-08-16 02:37:56.162 - info: host.iobroker-NAS instance system.adapter.hs100.0 started with pid 2810
2022-08-16 02:37:58.601 - info: hs100.0 (2810) starting. Version 2.1.2 in /opt/iobroker/node_modules/iobroker.hs100, node: v16.16.0, js-controller: 4.0.23

`

**Comment by neunteufels** [comment]
In my system the adapter is still stable...

**Comment by neunteufels** [comment]
Since the update the adapter is stable again.
I will not report further. For me this issue can be closed.

**Comment by Bender275** [comment]
Hi, unfortunatelly, the adapter also crashes at Raspi and iobroker:
<html><body>


hs100.0 | 2022-09-04 20:00:29.153 | info | Start with IP : 10.0.0.116
-- | -- | -- | --
hs100.0 | 2022-09-04 20:00:28.829 | info | Start with IP : 10.0.0.115
hs100.0 | 2022-09-04 20:00:28.784 | info | starting. Version 2.1.2 in /opt/iobroker/node_modules/iobroker.hs100, node: v16.17.0, js-controller: 4.0.23
hs100.0 | 2022-09-04 19:59:55.667 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hs100.0 | 2022-09-04 19:59:55.665 | info | terminating
hs100.0 | 2022-09-04 19:59:55.664 | info | cleaned everything up...
hs100.0 | 2022-09-04 19:59:55.659 | error | TCP Timeout after 10000ms10.0.0.115:9999 {"emeter":{"get_daystat":{"year":2022,"month":9}}}
hs100.0 | 2022-09-04 19:59:55.659 | error | Error:  TCP Timeout after 10000ms10.0.0.115:9999  {"emeter":{"get_daystat":{"year":2022,"month":9}}}    at  Timeout._onTimeout  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)     at listOnTimeout (node:internal/timers:559:17)    at processTimers  (node:internal/timers:502:7)
hs100.0 | 2022-09-04 19:59:55.658 | error | unhandled promise rejection: TCP Timeout after 10000ms10.0.0.115:9999 {"emeter":{"get_daystat":{"year":2022,"month":9}}}
hs100.0 | 2022-09-04 19:59:55.658 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>

All updates installed, Node.js v16.17.
It crashes about every 1-2 days. No actions waere taken at the plugs or the system.

**Comment by arteck** [comment]
the problem ist the tcp-socket connection.. when the plug send no answer to the adapter and the dependency tplink-smarthome-api crashed

**Comment by Bender275** [comment]
OK, thanks for the information. I assume, there is nothing I can do against it - so I will put a timeout in the adapter monitoring.

**Comment by neunteufels** [comment]
@Bender275 
What is adapter monitoring?
What is the timeour in it?

**Comment by Bender275** [comment]
@neunteufels 
There is no buildin monitoring of the adapters at iobroker.
I wrote a blockly script to check <instance>.0.alive whether channelname is online. If not, I got a notification.
With the timeout, I catch the short adapter restarts of the mentioned crashes.

**Comment by neunteufels** [comment]
@Bender275 
Thanks for you reply.
Fully understood. I got something similary with Blockly as well.

**Comment by erlanger24** [comment]
I do have the same issue.

<html>
<body>


2022-10-14 03:56:48.670 - info: node-red.0 (29102) State value to set for "pvforecast.0.nextHours.over_next_hour" has to be type "number" but received type "string"
--
2022-10-14 03:57:48.672 - info: node-red.0 (29102) State value to set for "pvforecast.0.nextHours.over_next_hour" has to be type "number" but received type "string"
2022-10-14 03:58:48.675 - info: node-red.0 (29102) State value to set for "pvforecast.0.nextHours.over_next_hour" has to be type "number" but received type "string"
2022-10-14 03:59:07.969 - error: hs100.0 (19178) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-14 03:59:07.979 - error: hs100.0 (19178) unhandled promise rejection: TCP Timeout after 10000ms
192.168.178.64:9999 {"emeter":{"get_daystat":{"year":2022,"month":10}}}
2022-10-14 03:59:07.980 - error: hs100.0 (19178) Error: TCP Timeout after 10000ms
192.168.178.64:9999 {"emeter":{"get_daystat":{"year":2022,"month":10}}}
at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-10-14 03:59:07.980 - error: hs100.0 (19178) TCP Timeout after 10000ms
192.168.178.64:9999 {"emeter":{"get_daystat":{"year":2022,"month":10}}}
2022-10-14 03:59:07.982 - info: hs100.0 (19178) cleaned everything up...
2022-10-14 03:59:07.982 - info: hs100.0 (19178) terminating
2022-10-14 03:59:07.983 - warn: hs100.0 (19178) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-14 03:59:08.571 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[1]: TCP 192.168.178.64:9999 Error: TCP Timeout after 10000ms
2022-10-14 03:59:08.575 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[1]: 192.168.178.64:9999 {"emeter":{"get_daystat":{"year":2022,"month":10}}}
2022-10-14 03:59:08.575 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-10-14 03:59:08.576 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[1]: at listOnTimeout (internal/timers.js:557:17)
2022-10-14 03:59:08.576 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[1]: at processTimers (internal/timers.js:500:7)
2022-10-14 03:59:08.577 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[2]: [A116-Strom Trockner] device.send() Error: TCP Timeout after 10000ms
2022-10-14 03:59:08.577 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[2]: 192.168.178.64:9999 {"emeter":{"get_daystat":{"year":2022,"month":10}}}
2022-10-14 03:59:08.577 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[2]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
2022-10-14 03:59:08.577 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[2]: at listOnTimeout (internal/timers.js:557:17)
2022-10-14 03:59:08.577 - error: host.DESKTOP-2U9VGNF(SmartHome) Caught by controller[2]: at processTimers (internal/timers.js:500:7)
2022-10-14 03:59:08.578 - error: host.DESKTOP-2U9VGNF(SmartHome) instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-10-14 03:59:08.578 - info: host.DESKTOP-2U9VGNF(SmartHome) Restart adapter system.adapter.hs100.0 because enabled
2022-10-14 03:59:38.661 - info: host.DESKTOP-2U9VGNF(SmartHome) instance system.adapter.hs100.0 started with pid 2288
2022-10-14 03:59:39.523 - info: hs100.0 (2288) starting. Version 2.1.2 in /opt/iobroker/node_modules/iobroker.hs100, node: v14.20.0, js-controller: 4.0.18
2022-10-14 03:59:39.542 - info: hs100.0 (2288) Start with IP : 192.168.178.64
2022-10-14 03:59:39.806 - info: hs100.0 (2288) Start with IP : 192.168.178.47
2022-10-14 03:59:39.818 - info: hs100.0 (2288) Start with IP : 192.168.178.45
2022-10-14 03:59:39.852 - info: hs100.0 (2288) Start with IP : 192.168.178.44
2022-10-14 03:59:39.862 - info: hs100.0 (2288) Start with IP : 192.168.178.77


</body>
</html>

**Comment by arteck** [comment]
check new version from GIT plz

**Comment by Bender275** [comment]
Thank you, I installed 2.1.3 from GIT, monitoring the situation

**Comment by Bender275** [comment]
Uh, long ago...
I think, at the adapter list, you select the cat at the top. Then the tab in the middle, from Github and select at the dropdown-list the hs100 adapter...

**Comment by Bender275** [comment]
New crashes yesterday, but since a long time:
<html><body>


hs100.0 | 2022-12-11 09:36:57.530 | error | Unexpected token u in JSON at position 0
-- | -- | -- | --
hs100.0 | 2022-12-11 09:36:57.530 | error | SyntaxError:  Unexpected token u in JSON at position 0    at JSON.parse  (<anonymous>)    at Plug.sendCommand  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/device/index.js:267:71)     at async Emeter.getRealtime  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/shared/emeter.js:70:55)
hs100.0 | 2022-12-11 09:36:57.529 | error | unhandled promise rejection: Unexpected token u in JSON at position 0
hs100.0 | 2022-12-11 09:36:57.528 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>

**Comment by arteck** [comment]
Unexpected token u in JSON at position 0

i found the same error in my log.. i thing the plug has a problem.. and send wrong json 
check new version

**Comment by Bender275** [comment]
Thank you very much! 2.1.6 installed now, I'll watch it.

**Comment by GoClyde** [comment]
Installed 2.1.6 yesterday.


<html><body>


hs100.0 | 2022-12-14 05:21:04.645 | info | starting.  Version 2.1.6 (non-npm: arteck/ioBroker.hs100) in  /opt/iobroker/node_modules/iobroker.hs100, node: v14.19.3,  js-controller: 4.0.23
-- | -- | -- | --
hs100.0 | 2022-12-14 05:20:31.319 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hs100.0 | 2022-12-14 05:20:31.318 | info | terminating
hs100.0 | 2022-12-14 05:20:31.317 | info | cleaned everything up...
hs100.0 | 2022-12-14 05:20:31.310 | error | TCP Timeout after 20000ms192.168.1.213:9999 {"emeter":{"get_realtime":{}}}
hs100.0 | 2022-12-14 05:20:31.310 | error | Error:  TCP Timeout after 20000ms192.168.1.213:9999  {"emeter":{"get_realtime":{}}}    at Timeout._onTimeout  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)     at listOnTimeout (internal/timers.js:557:17)    at processTimers  (internal/timers.js:500:7)
hs100.0 | 2022-12-14 05:20:31.309 | error | unhandled promise rejection: TCP Timeout after 20000ms192.168.1.213:9999 {"emeter":{"get_realtime":{}}}
hs100.0 | 2022-12-14 05:20:31.287 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>

**Comment by runrennerrun** [comment]
I still see the problem on my system - currently nearly daily: 
2023-02-15 18:46:01.885  - [31merror[39m: hs100.0 (16751) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-02-15 18:46:01.886  - [31merror[39m: hs100.0 (16751) unhandled promise rejection: TCP Timeout after 10000ms
192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
2023-02-15 18:46:01.886  - [31merror[39m: hs100.0 (16751) Error: TCP Timeout after 10000ms
192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2023-02-15 18:46:01.888  - [31merror[39m: hs100.0 (16751) TCP Timeout after 10000ms
192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
2023-02-15 18:46:01.892  - [32minfo[39m: hs100.0 (16751) cleaned everything up...
2023-02-15 18:46:01.894  - [32minfo[39m: hs100.0 (16751) terminating
2023-02-15 18:46:01.896  - [33mwarn[39m: hs100.0 (16751) Terminated (UNCAUGHT_EXCEPTION): Without reason

**Comment by runrennerrun** [comment]
> I still see the problem on my system - currently nearly daily: 
> 
> 2023-02-15 18:46:01.885  - [31merror[39m: hs100.0 (16751) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 
> 2023-02-15 18:46:01.886  - [31merror[39m: hs100.0 (16751) unhandled promise rejection: TCP Timeout after 10000ms
> 
> 192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
> 
> 2023-02-15 18:46:01.886  - [31merror[39m: hs100.0 (16751) Error: TCP Timeout after 10000ms
> 
> 192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
> 
>     at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
> 
>     at listOnTimeout (node:internal/timers:559:17)
> 
>     at processTimers (node:internal/timers:502:7)
> 
> 2023-02-15 18:46:01.888  - [31merror[39m: hs100.0 (16751) TCP Timeout after 10000ms
> 
> 192.168.178.31:9999 {"emeter":{"get_realtime":{}}}
> 
> 2023-02-15 18:46:01.892  - [32minfo[39m: hs100.0 (16751) cleaned everything up...
> 
> 2023-02-15 18:46:01.894  - [32minfo[39m: hs100.0 (16751) terminating
> 
> 2023-02-15 18:46:01.896  - [33mwarn[39m: hs100.0 (16751) Terminated (UNCAUGHT_EXCEPTION): Without reason

And again, with the same error. Am I the only one with this error?

**Comment by arteck** [comment]
no you are not alone..
the problem is.. the plug send wrong data. and this i not correct intercepted.. 
the problem is very old.. 

https://github.com/plasticrake/tplink-smarthome-api/issues/146

**Comment by Schaxxe** [comment]
Adapter is not working proberly since a few weeks

hs100.0 2023-04-22 15:16:11.282	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
hs100.0 2023-04-22 15:16:11.281	info	terminating
hs100.0 2023-04-22 15:16:11.281	info	cleaned everything up...
hs100.0 2023-04-22 15:16:11.280	error	TCP Timeout after 10000msxxx:9999 {"emeter":{"get_realtime":{}}}
hs100.0 2023-04-22 15:16:11.280	error	Error: TCP Timeout after 10000msxxx:9999 {"emeter":{"get_realtime":{}}} at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
hs100.0 2023-04-22 15:16:11.280	error	unhandled promise rejection: TCP Timeout after 10000ms1xxx:9999 {"emeter":{"get_realtime":{}}}
hs100.0 2023-04-22 15:16:11.279	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hs100.0 2023-04-22 15:15:00.732	info	Start with IP : xxx
hs100.0 2023-04-22 15:14:50.730	info	Start with IP : xxx
hs100.0 2023-04-22 15:14:50.710	info	Start with IP : xxx
hs100.0 2023-04-22 15:14:50.700	info	starting. Version 2.1.2 in /opt/iobroker/node_modules/iobroker.hs100, node: v16.20.0, js-controller: 4.0.24

**Comment by Bender275** [comment]
Hi, aktuell stürtzt bei mir der Adapter wieder mehrmals täglich ab :-(

Meldungen laut Log:

```
host.Raspi4 | 2024-06-02 11:49:18.967 | info | instance system.adapter.hs100.0 started with pid 37898
host.Raspi4 | 2024-06-02 11:48:48.867 | info | Restart adapter system.adapter.hs100.0 because enabled
host.Raspi4 | 2024-06-02 11:48:48.866 | error | instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught by controller[1]:     at TCP.<anonymous> (node:net:350:12)
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught by controller[1]:     at Socket.emit (node:events:517:28)
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught by controller[1]:     at Object.onceWrapper (node:events:632:26)
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught  by controller[1]:     at Socket.<anonymous>  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:103:31)
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught by controller[1]: [WaschkellerWaschmaschine] device.send() Error: TCP Socket Closed. segment:0 hadError:false
host.Raspi4 | 2024-06-02 11:48:48.866 | error | Caught by controller[0]:     at TCP.<anonymous> (node:net:350:12)
host.Raspi4 | 2024-06-02 11:48:48.865 | error | Caught by controller[0]:     at Socket.emit (node:events:517:28)
host.Raspi4 | 2024-06-02 11:48:48.865 | error | Caught by controller[0]:     at Object.onceWrapper (node:events:632:26)
host.Raspi4 | 2024-06-02 11:48:48.865 | error | Caught  by controller[0]:     at Socket.<anonymous>  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:103:31)
host.Raspi4 | 2024-06-02 11:48:48.864 | error | Caught by controller[0]: TCP 10.0.0.115:9999 Error: TCP Socket Closed. segment:0 hadError:false
hs100.0 | 2024-06-02 11:48:48.744 | info | terminating
hs100.0 | 2024-06-02 11:48:48.240 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hs100.0 | 2024-06-02 11:48:48.238 | info | terminating
hs100.0 | 2024-06-02 11:48:48.236 | info | cleaned everything up...
hs100.0 | 2024-06-02 11:48:48.228 | error | TCP Socket Closed. segment:0 hadError:false
hs100.0 | 2024-06-02 11:48:48.228 | error | Error:  TCP Socket Closed. segment:0 hadError:false    at  Socket.<anonymous>  (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:103:31)     at Object.onceWrapper (node:events:632:26)    at Socket.emit  (node:events:517:28)    at TCP.<anonymous> (node:net:350:12)
hs100.0 | 2024-06-02 11:48:48.227 | error | unhandled promise rejection: TCP Socket Closed. segment:0 hadError:false
hs100.0 | 2024-06-02 11:48:48.226 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
```

Das Ziehen und Stecken der beiden Steckdosen hilft leider auch nciht dauerhaft...
Jemand ne Idee?

**Comment by arteck** [comment]
plz check new version
