### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by UweRP** [arteck/ioBroker.hs100#243]
Unter js-controller 6.0.6 werden Restart loop gemeldet und der Adapter deaktiviert

`2024-07-12 14:35:21.991  - [32minfo[39m: hs100.0 (11696) starting. Version 2.2.0 in c:/iobroker/node_modules/iobroker.hs100, node: v20.15.1, js-controller: 6.0.6
2024-07-12 14:35:22.005  - [32minfo[39m: hs100.0 (11696) Start with 10.111.112.52 52-Kaffee 
2024-07-12 14:35:23.117  - [32minfo[39m: homee.0 (4644) initialize 1 nodes
2024-07-12 14:35:25.407  - [32minfo[39m: hs100.0 (11696) Start with 10.111.112.105 105-Heißluft 
2024-07-12 14:35:49.155  - [31merror[39m: hs100.0 (11696) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-07-12 14:35:49.155  - [31merror[39m: hs100.0 (11696) unhandled promise rejection: TCP Timeout after 20000ms
10.111.112.52:9999 {"emeter":{"get_daystat":{"year":2024,"month":7}}}
2024-07-12 14:35:49.155  - [31merror[39m: hs100.0 (11696) Error: TCP Timeout after 20000ms
10.111.112.52:9999 {"emeter":{"get_daystat":{"year":2024,"month":7}}}
    at Timeout._onTimeout (c:\iobroker\node_modules\tplink-smarthome-api\lib\network\tcp-socket.js:59:36)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
2024-07-12 14:35:49.155  - [31merror[39m: hs100.0 (11696) TCP Timeout after 20000ms
10.111.112.52:9999 {"emeter":{"get_daystat":{"year":2024,"month":7}}}
2024-07-12 14:35:49.157  - [32minfo[39m: hs100.0 (11696) cleaned everything up...
2024-07-12 14:35:49.157  - [32minfo[39m: hs100.0 (11696) terminating
2024-07-12 14:35:49.158  - [33mwarn[39m: hs100.0 (11696) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-07-12 14:35:49.668  - [32minfo[39m: hs100.0 (11696) terminating
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[0]: TCP 10.111.112.52:9999 Error: TCP Timeout after 20000ms
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[0]: 10.111.112.52:9999 {"emeter":{"get_daystat":{"year":2024,"month":7}}}
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[0]:     at Timeout._onTimeout (c:\iobroker\node_modules\tplink-smarthome-api\lib\network\tcp-socket.js:59:36)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[0]:     at listOnTimeout (node:internal/timers:573:17)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[0]:     at process.processTimers (node:internal/timers:514:7)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[1]: [Kaffee] device.send() Error: TCP Timeout after 20000ms
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[1]: 10.111.112.52:9999 {"emeter":{"get_daystat":{"year":2024,"month":7}}}
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[1]:     at Timeout._onTimeout (c:\iobroker\node_modules\tplink-smarthome-api\lib\network\tcp-socket.js:59:36)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[1]:     at listOnTimeout (node:internal/timers:573:17)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU Caught by controller[1]:     at process.processTimers (node:internal/timers:514:7)
2024-07-12 14:35:49.774  - [31merror[39m: host.DESKTOP-77OGRTU instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-07-12 14:35:49.775  - [32minfo[39m: host.DESKTOP-77OGRTU Restart adapter system.adapter.hs100.0 because enabled
2024-07-12 14:35:49.775  - [33mwarn[39m: host.DESKTOP-77OGRTU Do not restart adapter system.adapter.hs100.0 because restart loop detected
2024-07-12 14:35:49.796  - [32minfo[39m: notification-manager.0 (10208) Send notification "system.restartLoop" to "email.0"
2024-07-12 14:35:49.807  - [32minfo[39m: email.0 (9908) New notification received from system.adapter.notification-manager.0
2024-07-12 14:35:49.893  - [32minfo[39m: email.0 (9908) Send email: {"subject":"Probleme mit häufig abstürzenden Adapterinstanzen","text":"Eine Adapterinstanz stürzt beim Start häufig ab und wurde aus diesem Grund gestoppt. Die Protokolldatei muss vor dem Neustart der Instanz überprüft werden.\n\nsystem.host.DESKTOP-77OGRTU:   \nhs100.0: 12.7.2024, 14:35:49 Restart loop detected\n    `

**Comment by arteck** [comment]
same
https://github.com/arteck/ioBroker.hs100/issues/157
