### ISSUE TITLE
Version 1.0.8 Fehler unter Windows 10

### ISSUE THREAD

**Issue by UweRP** [arteck/ioBroker.hs100#37]
Wenn ich den Adapter auf die Version 1.0.8 update  sind die Steckdosen nicht mehr ansprechbar.
Werden die Objekte und Adapter gelöscht und neu installiert werden auch keine Objekte mehr angelegt.
Die Version 1.0.6 funktioniert.
Diese Fehlermeldung konnt ich dazu finden:

`2018-12-15 08:06:33.728  - [32minfo[39m: hs100.0 starting. Version 1.0.8 in C:/ioBroker/node_modules/iobroker.hs100, node: v6.15.1
2018-12-15 08:06:33.743  - [31merror[39m: hs100.0 uncaught exception: Cannot read property 'length' of undefined
2018-12-15 08:06:33.744  - [31merror[39m: hs100.0 TypeError: Cannot read property 'length' of undefined
    at main (C:\ioBroker\node_modules\iobroker.hs100\main.js:619:32)
    at Object.ready (C:\ioBroker\node_modules\iobroker.hs100\main.js:30:9)
    at initAdapter (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:5289:62)
    at createInstancesObjects (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:830:13)
    at Socket.that.getForeignObject (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:869:25)
    at Socket.onack (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
    at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
    at Manager.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
    at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
2018-12-15 08:06:34.252  - [32minfo[39m: hs100.0 terminating
2018-12-15 08:06:34.270  - [31merror[39m: Caught by controller[0]: TypeError: Cannot read property 'length' of undefined
2018-12-15 08:06:34.270  - [31merror[39m: Caught by controller[0]:     at main (C:\ioBroker\node_modules\iobroker.hs100\main.js:619:32)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Object.ready (C:\ioBroker\node_modules\iobroker.hs100\main.js:30:9)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at initAdapter (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:5289:62)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at createInstancesObjects (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:830:13)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Socket.that.getForeignObject (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:869:25)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Socket.onack (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:312:9)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:236:12)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Manager.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
2018-12-15 08:06:34.271  - [31merror[39m: Caught by controller[0]:     at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
2018-12-15 08:06:34.271  - [31merror[39m: host.HP-ED800 instance system.adapter.hs100.0 terminated with code 0 (OK)
2018-12-15 08:06:34.271  - [32minfo[39m: host.HP-ED800 Restart adapter system.adapter.hs100.0 because enabled
`

Kannst du was damit anfangen oder brauchst du mehr Infos?

**Comment by arteck** [comment]
da sind keine Steckdosen definiert
