### ISSUE TITLE
Connection to LB130 timeouts

### ISSUE THREAD

**Issue by Byolock** [arteck/ioBroker.hs100#51]
It worked just fine a week ago. But today i recognised that the values of my LB130 do not refresh. Found the following in the Log : 

```
2019-12-17 16:49:08.334  - info: host.iobroker instance system.adapter.hs100.0 started with pid 11290
--
2019-12-17 16:49:08.553  - info: hs100.0 starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.hs100, node: v10.17.0
2019-12-17 16:49:37.402  - info: host.iobroker object change system.adapter.hs100.0
2019-12-17 16:49:37.402  - info: host.iobroker stopInstance system.adapter.hs100.0
2019-12-17 16:49:37.402  - info: host.iobroker stopInstance system.adapter.hs100.0 killing pid 11290
2019-12-17 16:49:37.412  - error: Caught by controller[0]: TCP Timeout
2019-12-17 16:49:37.412  - error: Caught by controller[0]: (node:11290) UnhandledPromiseRejectionWarning: Error: TCP Timeout
2019-12-17 16:49:37.412  - error:  Caught by controller[0]:     at Timeout.setTimeout [as _onTimeout]  (/opt/iobroker/node_modules/iobroker.hs100/node_modules/tplink-smarthome-api/lib/client.js:226:20)
2019-12-17 16:49:37.412  - error: Caught by controller[0]:     at ontimeout (timers.js:436:11)
2019-12-17 16:49:37.412  - error: Caught by controller[0]:     at tryOnTimeout (timers.js:300:5)
2019-12-17 16:49:37.412  - error: Caught by controller[0]:     at listOnTimeout (timers.js:263:5)
2019-12-17 16:49:37.412  - error: Caught by controller[0]:     at Timer.processTimers (timers.js:223:10)
2019-12-17 16:49:37.413  - error:  Caught by controller[0]: (node:11290) UnhandledPromiseRejectionWarning:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch(). (rejection id: 1)
2019-12-17 16:49:37.413  - error:  Caught by controller[0]: (node:11290) [DEP0018] DeprecationWarning:  Unhandled promise rejections are deprecated. In the future, promise  rejections that are not handled will terminate the Node.js process with a  non-zero exit code.
2019-12-17 16:49:37.413  - error: Caught by controller[1]: TCP Timeout
2019-12-17 16:49:37.413  - error: Caught by controller[2]: TCP Timeout
2019-12-17 16:49:37.413  - info: host.iobroker instance system.adapter.hs100.0 terminated with code 156 ()
```

The LB130 can be pinged from iobroker and controlled through the app.
A HS100 connected to the same instance works fine.

If you need any more log Files or so please reach out to me.

**Comment by arteck** [comment]
TCP Timeout .. WLAN temporary unavailable ??
