### ISSUE TITLE
seit JS-Controller 3.1.4 Errors

### ISSUE THREAD

**Issue by Negalein** [arteck/ioBroker.hs100#65]
seit Update auf 3.1.4 bekomm ich sehr oft (mal jede Minute, mal alle halbe Stunde, ...) diese Fehler.
Kommt vom HS100-Adapter.

Vor dem Update waren diese Fehler nicht da.
Liegt das am HS100 oder am JS-Controller?

```
Heute 12:06	error	host.iobroker	Caught by controller[0]: TCP 10.0.1.79:9999 Error: TCP Socket Closed. segment:0 hadError:false
Heute 12:06	error	hs100.0	Error: TCP Socket Closed. segment:0 hadError:false at Socket.socket.once.hadError (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19) at Object.onceWrapper (events.js:286:20) at Socket.emit (events.js:198:13) at TCP._handle.close (net.js:607:12)
Heute 12:06	error	hs100.0	unhandled promise rejection: TCP Socket Closed. segment:0 hadError:false
Heute 12:06	error	hs100.0	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
Heute 12:04	error	host.iobroker	Caught by controller[1]: TCP 10.0.1.80:9999 Error: TCP Socket Closed. segment:0 hadError:false
Heute 12:04	error	hs100.0	Error: TCP Socket Closed. segment:0 hadError:false at Socket.socket.once.hadError (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19) at Object.onceWrapper (events.js:286:20) at Socket.emit (events.js:198:13) at TCP._handle.close (net.js:607:12)
Heute 12:04	error	hs100.0	unhandled promise rejection: TCP Socket Closed. segment:0 hadError:false
Heute 12:04	error	hs100.0	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by arteck** [comment]
fehler liegt auf seite tplink-smarthome-api..da kann ich nix machen

**Comment by arteck** [comment]
https://github.com/arteck/ioBroker.hs100/issues/59

**Comment by arteck** [comment]
version 2.0.0
