### ISSUE TITLE
LB set Power State Socket Timeout

### ISSUE THREAD

**Issue by weindler** [arteck/ioBroker.hs100#85]
Hi, seit heute habe ich folgende Warnmeldung im log vom iobroker,

```

hs100.0 | 2021-02-09 17:07:20.140 | warn | at TCP._handle.close (net.js:607:12)
-- | -- | -- | --
hs100.0 | 2021-02-09 17:07:20.140 | warn | at Socket.emit (events.js:198:13)
hs100.0 | 2021-02-09 17:07:20.140 | warn | at Object.onceWrapper (events.js:286:20)
hs100.0 | 2021-02-09 17:07:20.140 | warn | at Socket.socket.once (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
hs100.0 | 2021-02-09 17:07:20.140 | warn | (920) Info Message setDevice: Error: TCP Socket Closed. segment:0 hadError:false
hs100.0 | 2021-02-09 17:07:05.099 | warn | at TCP._handle.close (net.js:607:12)
hs100.0 | 2021-02-09 17:07:05.099 | warn | at Socket.emit (events.js:198:13)
hs100.0 | 2021-02-09 17:07:05.099 | warn | at Object.onceWrapper (events.js:286:20)
hs100.0 | 2021-02-09 17:07:05.099 | warn | at Socket.socket.once (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
hs100.0 | 2021-02-09 17:07:05.099 | warn | (920) Info Message setDevice: Error: TCP Socket Closed. segment:0 hadError:false
hs100.0 | 2021-02-09 17:07:05.092 | warn | at TCP._handle.close (net.js:607:12)
hs100.0 | 2021-02-09 17:07:05.092 | warn | at Socket.emit (events.js:198:13)
hs100.0 | 2021-02-09 17:07:05.092 | warn | at Object.onceWrapper (events.js:286:20)
hs100.0 | 2021-02-09 17:07:05.092 | warn | at Socket.socket.once (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
hs100.0 | 2021-02-09 17:07:05.092 | warn | (920) Info Message setDevice: Error: TCP Socket Closed. segment:0 hadError:false


hs100.0 | 2021-02-09 16:53:50.111 | warn | (920) LB setPowerState Socket connection Timeout : 192.168.***.**
-- | -- | -- | --
```

Node.js
    v10.23.2
NPM
    6.14.10
Läuft eigentlich seit 3 Monaten stabil und ohne Fehlermeldungen, bis auf heute.

Gruß

**Comment by weindler** [comment]
Habe den Fehler selber gefunden, zuoft abgefragt, alle 15 Sekunden, seitdem auf 10 Minuten gestellt ist ist alles gut. Damit schließe ich das Issue
